version: '1'

service:
  app:
    image: 'order-management-system:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/data
      - SPRING_DATASOURCE_USERNAME=zopeaj
      - SPRING_DATASOURCE_PASSWORD=admin124
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=zopeaj
      - POSTGRES_PASSWORD=admin124

